# ====================================================================================
# Action metadata
name: API insights CLI - Brew
author: Treblle
description: Get insights into your OpenAPI specifications and API using the Treblle CLI.
branding:
  icon: terminal
  color: blue

# ====================================================================================
# Action
on:
  pull_request:
      branches: [ develop, release, main ]
      types: [opened, synchronize]

jobs:
  insight:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Set up Homebrew taps
      run: |
        brew tap treblle/treblle

    - name: Install dependencies
      run: |
        brew install treblle

    - name: Run tests
      run: treblle-cli insights openapi-spec.json -m 45
